language: php

php:
  - 8.0
  - 7.4
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4
    - php: 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose
